### ISSUE TITLE
metahandler error

### ISSUE THREAD

**Issue by thwaller** [Eldorados/script.module.metahandler#2]
Errors such as this appear often in the Kodi log.
22:36:47 T:139855401051904   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized

Have tried 2.9.0 and 2.9.1, both result in the same. 2.9.1 from Mucky Ducks Repo. What is the cause / fix?

**Comment by Eldorados** [comment]
Which addon is this for?

Metahandlers no longer supplies it's own api key for TMDB, the addon must
now get it's own and pass it into Metahandlers to properly pull from TMDB

**Comment by thwaller** [comment]
This is for Kodi. The addon that is available from the Kodi repository. I am unsure how the above is supposed to happen, but it prompts me for nothing. The reported errors just appear in the log many times.

**Comment by Eldorados** [comment]
Yes I know it's for Kodi

But what addon are you using that makes this message display? Metahandlers
doesn't run on it's own, an addon must call it to run... so what addon are
you running?

**Comment by thwaller** [comment]
Sorry for the misunderstanding. I am unsure, I run a lot of addons. It believe it would be 1channel based on this segment, containing 1channel items before and after:
09:59:16 T:140320532588288  NOTICE: 1Channel: Loading sqlite3 as DB engine
09:59:16 T:140319817377536  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.1
09:59:16 T:140319817377536  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.11.0
09:59:16 T:140319624324864  NOTICE: Previous line repeats 1 times.
09:59:16 T:140319624324864  NOTICE: 1Channel: Loading sqlite3 as DB engine
09:59:16 T:140319817377536   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
09:59:17 T:140319624324864   ERROR: Previous line repeats 2 times.
09:59:17 T:140319624324864  NOTICE: metahandler: No SQLite rows requiring update
09:59:17 T:140319624324864  NOTICE: 1Channel: Version: |2.5.69| Queries: |{'mode': 'movie_update'}|
09:59:17 T:140319624324864  NOTICE: 1Channel: Args: |['plugin://plugin.video.1channel/', '-1', '?mode=movie_update']|

IF that is correct, this sould be reported with that addon rather than here?

**Comment by Eldorados** [comment]
Yes it's 1Channel, that addon needs to get it's own api key to use with
metahandlers, there's nothing I can do about it

**Comment by thwaller** [comment]
Understood.

**Comment by thwaller** [comment]
Is it possible to use my API key? If so, how might I do that? Referring to with metahandlers itself.

**Comment by tknorris** [comment]
@Eldorados Can we just add a setting to methandler to allow the user to put in their API key? You and I both know if I request a TMDB key for 1CH it'll just be rejected/revoked.

**Comment by Eldorados** [comment]
I can, not too big of a deal to do... though I'm doubtful many users will
go this route

Wondering how did Lambda get his Genesis/Exodus key?

One of these days I was going to apply for a new key for Icefilms, he's not
actively against our stuff, but will shut us down if he's told to do so

**Comment by thwaller** [comment]
>  though I'm doubtful many users will go this route

Is there an issue with a user doing so? I can easily use my key, it is used on another addon that asks for it.

**Comment by Eldorados** [comment]
Nope no issue, and no problem adding it.. just not positive on how many
users would be like you and knowing enough to do so

**Comment by tknorris** [comment]
All of lambdas keys are revoked. He had to rewrite Exodus because of it...he certainly seems to be against something

**Comment by Eldorados** [comment]
Ah.. that actually doesn't surprise me, with the amount of traffic he must
generate

There is another idea, but I'll catch you on unseen about it

**Comment by thwaller** [comment]
Just my opinion...if it would solve the issue with all addons using metahandlers, it would be nice to have this feature.

**Comment by Eldorados** [comment]
It won't solve it, but will at least give the user an option.. though ideal
solution is for the addon itself to have it's own key, might not be
feasible to do so any more

**Comment by thwaller** [comment]
I see what you mean. It will give the user a method to solve it, not solve it on its own.

**Comment by tknorris** [comment]
@thwaller Until eldorado adds a setting, if you add your tmdb api key to this [line](https://github.com/Eldorados/script.module.metahandler/blob/master/lib/metahandler/metahandlers.py#L96), metahandler should use it unless the addon overrides it (1CH doesn't).

**Comment by thwaller** [comment]
@tknorris Thanks. I was just looking at that myself. I will do so, thanks.

**Comment by thwaller** [comment]
As the issue is known, I am closing. Using my key is working just fine. For me, it is easy enough to just maintain with this method and do manual updates to the script as needed. Thanks to both.
