### ISSUE TITLE
Error attempting to insert into movie_meta cache table: database is locked

### ISSUE THREAD

**Issue by crispybishop** [Eldorados/script.module.metahandler#36]
Running PseudoTV Live to parse Genesis channels, I reach a "database locked" error along the way. Then it stops writing to the video_cache, creating a db-journal file.

Log posted here: http://forum.kodi.tv/showthread.php?tid=169032&pid=1838776#pid1838776

**Comment by crispybishop** [comment]
Was this fixed?

**Comment by Eldorados** [comment]
There's really nothing for me to fix, db lockups happen on the rare
occasion, and when they do there doesn't seem to be a conclusive trigger...
to fix the lock all you need to do is reboot xbmc
