### ISSUE TITLE
Update change log for version 3.99

### ISSUE THREAD

**Issue by kekukui** [Eldorados/script.module.metahandler#4]
Change log has not been updated since 2.9.0
https://github.com/Eldorados/script.module.metahandler/blob/master/changelog.txt

Kodi official repo still offers 2.9.0
All other actively-maintained repos are using 3.0.2, except Gaia

What is the benefit of using 3.99, and why the jump in versioning from 3.0.2 to 3.99 ?

**Comment by Cyber1000** [comment]
I think that's a preparation for 4.0, with much space in between for bugfixing, but that's only guessing.
Besides of that it should read 3.99.2 and not 3.99.02. 02 may not be a valid versioning scheme, at least it looks weird.

**Comment by Eldorados** [comment]
Yeah the current version really wasn't meant to be released as it but others decided to grab and distribute it, I should probably have done more to make it obvious this wasn't ready to go out

I'll update when I do a 4.0 which was my ultimate version for all the updates
