### ISSUE TITLE
tvdb language support for episode meta info

### ISSUE THREAD

**Issue by traphyl** [Eldorados/script.module.metahandler#40]
Hello,

the language support for meta-data in episodes doesn't work. I tried it with german language and the series "Arrow" and some others. Metahandler shows german meta-data for the series itself but not for the particular episodes. Is it possible to fix this anytime?

Thanks a lot.

**Comment by Eldorados** [comment]
This must have been overlooked when it was added, should be easy to do

**Comment by Eldorados** [comment]
Done in - 42abc33b882e0dc59ab3f753ff0eec95454f8c00
